[metadata]
name = lightgpt
version = 1.0.0
description = LightGPT lightweight GPT
author = Maor-404
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
classifiers =
    Development Status :: 5 - Production/Stable
    Intended Audience :: Developers
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Topic :: Scientific/Engineering :: Artificial Intelligence

[options]
packages = find:
package_dir =
    = src
install_requires =
    torch>=1.12.0
    transformers>=4.20.0
    onnx>=1.12.0
    onnxruntime>=1.12.0
    sentencepiece>=0.1.96
    numpy>=1.21.0
    wikipedia>=1.4.0
    huggingface_hub>=0.23.0

[options.packages.find]
where = src
