[metadata]
name = lightgpt
version = 0.1.0
description = LightGPT lightweight GPT
author = Maor-404

[options]
packages = find:
package_dir =
    = src
install_requires =
    torch>=2.0.0
    numpy
    sentencepiece
    transformers>=4.30.0
    datasets
    onnx
    onnxruntime

[options.packages.find]
where = src
